name: flutter_dom2
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependency_resolution:
  # Set the maximum depth of package resolution.
  max_depth: 4

#----- Packages ------#
dependencies:
  controller: ^0.1.10+1
  json_annotation: ^4.8.0
  qrscan: ^0.3.3
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.5.3
  

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  mobile_scanner: ^4.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_config: ^2.0.2

  # Product Specific

  #----- Packages END ------#

dev_dependencies:
  build_runner: ^2.3.3
  controller_generator: ^0.1.8
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #-------- Local Assets -------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/category/
    - assets/images/

  # -------- Local Fonts -----------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-BoldItalic.ttf

        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\Poppins-LightItalic.ttf

        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
